Разметка главной страницы
htmlacademy-htmlcss/1438629-sedona-33 pull request #3
Opened 2022-01-24 18:36 UTC by AndreyOzeev

2022-01-24 18:37 UTC, AndreyOzeev commented
Разметка главной страницы, начало разметки страницы каталога

2022-01-25 15:32 UTC, costigans requested changes

2022-01-25 15:32 UTC, costigans commented on index.html
> +      <a href="index.html">
Есть одно хорошее правило — страница не должна ссылаться на саму себя.
Поэтому здесь, а так же в пункте  «Главная» убери аттрибут `href`.

2022-01-25 15:32 UTC, costigans commented on index.html
> +                  <input class="order-button" type="submit" value="Хочу сюда">
`input` используется только в формах.

2022-01-25 15:32 UTC, costigans commented on index.html
> +        <h2 class="about-sedona">Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
Два заголовка `h2` рядом? Что-то не то

2022-01-25 15:32 UTC, costigans commented on index.html
> +            <p class="advantages-number">— №1 —</p>
То, что это список, ты абсолютно верно определил, только это нумерованный список (1, 2, 3 ...). №1 и т.п. это стилизация списка, и она задаётся через псевдоэлементы (об этом позже). Поэтому я рекомендую убрать тебе эти параграфы `advantages-number`

2022-01-25 15:32 UTC, costigans commented on index.html
> +        <input class="search-hotel-button" type="submit" value="Поиск гостиницы в Седоне">
Не `input`

2022-01-25 15:32 UTC, costigans commented on index.html
> +          <label for="newsletter-email">Email</label>
«Ваш e-mail»

2022-01-25 15:32 UTC, costigans commented on index.html
> +          <input class="mailing-button" type="submit" value="Подписаться">
Тоже не `input`, есть более подходящий элемент для отправки формы.
`input` это «поле ввода»

2022-01-25 15:32 UTC, costigans commented on index.html
> +        <address class="phone-number">
А точно `address`?

2022-01-25 15:32 UTC, costigans commented on index.html
> +        <p class="about-text"><a class="htmlacademy-link" href="https://htmlacademy.ru/">.html academy</a></p>
Текст ссылки не тот

2022-01-25 15:32 UTC, costigans commented on catalog.html
> +    	  </fieldset>
Отступы куда-то поехали. Следи за этим

2022-01-25 15:32 UTC, costigans commented on catalog.html
> +		<h2 class="sorting-title">Найдено гостиниц: 38</h2>
Точно ли такой заголовок? О чём этот раздел? Это и выноси в заголовок, он может быть визуально скрытым

2022-01-28 08:57 UTC, costigans approved these changes
Ответь на вопросы, в остальном ок

2022-01-28 08:57 UTC, costigans commented on index.html
> +        <h3 class="about-sedona">Седона — небольшой городок в Аризоне, заслуживающий большего!</h3>
Нужен ли тут заголовок? Какой смысл он приносит?

2022-01-28 08:57 UTC, costigans commented on index.html
> +            <span class="mailing-button-style">Подписаться</span>
Зачем здесь `span`?

2022-01-28 08:57 UTC, merged

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +<html lang="en">
Неверное значение атрибута

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +	<title>Седона "Каталог"</title>
Каталог гостиниц

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +					<a class="navigation-link" href="faq.html">О Седоне</a>
У тебя нет `faq.html`

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +					<a class="breadcrumbs-link" href="catalog.html">Каталог</a>
Страница на саму себя не ссылается

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +			<h2 class="block-title">Инфраструктура:</h2>
Только ли про инфраструктуру речь в этом блоке?

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +				<h2 class="filter-cost">Стоимость</h2>
Это не заголовок

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +				<input class="control-cost" type="range" min="0" max="9000">
А где поля «от» и «до»?

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +				<button class="button-cansel" type="reset">Сбросить</button>
cancel

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +			</a>
Это однородные элементы (варианты отображения), может в список?

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +						<span class="visually-hidden">10</span>
Для чего этот спан?

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +			<ul class="pagination">
Не хватает скрытого заголовка объясняющего, что это за список чисел?

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +					<a class="pagination-link pagination-next" href="#">...</a>
Не next

2022-01-28 11:52 UTC, costigans commented on catalog.html
> +					<span class="mailing-button-style">Подписаться</span>
Для чего sspan?

2022-01-28 14:53 UTC, AndreyOzeev commented on index.html
> +            <span class="mailing-button-style">Подписаться</span>
Для стилизации думал использовать, но лучше через button. Уберу

2022-01-30 13:48 UTC, AndreyOzeev commented on index.html
> +        <h3 class="about-sedona">Седона — небольшой городок в Аризоне, заслуживающий большего!</h3>
Скорее нет, выше заголовок есть, этот вполне можно сделать параграфом описывающим Седону

2022-01-30 13:51 UTC, AndreyOzeev commented on catalog.html
> +					<a class="navigation-link" href="faq.html">О Седоне</a>
Но есть такая ссылка в макете, я обозначил ее на будущее, если будет в ней необходимость