Задание 3.22 Базовая стилизация всех страниц
htmlacademy-htmlcss/1438629-sedona-33 pull request #6
Opened 2022-02-09 18:10 UTC by AndreyOzeev

2022-02-09 20:42 UTC, costigans requested changes

2022-02-09 20:42 UTC, costigans commented on styles/styles.css
> +    background-color: white;
При таком фоне часть изображения с англ. текстом сливается.
Для защитного фонового цвета бери преобладающий или средний цвет с изображения-фона.

2022-02-09 20:42 UTC, costigans commented on styles/styles.css
> +    background-color: #83B3D3;
Удачно подобрал цвет 👍

2022-02-09 20:42 UTC, costigans commented on catalog.html
> +				<button class="button-cancel" type="reset">Сбросить</button>
Не нашёл стилей для этой кнопки

2022-02-09 20:42 UTC, costigans commented on styles/styles.css
> +}
А где фон?

2022-02-09 20:42 UTC, costigans commented on catalog.html
> +			</header>
Это не хедер, у тебя уже есть. Здесь использовать хедер — лишнее.

2022-02-09 20:42 UTC, costigans commented on styles/styles.css
> +.button-list {
Может проще дать один класс и использовать его?

2022-02-09 20:42 UTC, costigans commented on styles/styles.css
> +    background-image: url(../images/mailing-background.jpg);
Кавычки забыл

2022-02-09 20:42 UTC, costigans commented on styles/styles.css
> +    background-image: url(..//images/background-cataloge-filter.png);
Кавычки и лишний слэш

2022-02-10 15:24 UTC, AndreyOzeev commented on catalog.html
> +			</header>
Как в примере с барбершопом взял, но наверно лучше вообще убрать

2022-02-10 15:30 UTC, AndreyOzeev commented on styles/styles.css
> +.button-list {
А потом на каждую из них нужно будет разную иконку подгружать? Сейчас дам два класса, а базовую этих кнопок на один класс обозначу

2022-02-10 16:05 UTC, merged